/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodeDisarmResult {
  /** The mathematically safe, reconstructed byte stream, returned as a Node.js Buffer. */
  buffer: Buffer
  originalSizeBytes: number
  finalSizeBytes: number
  detectedFormat: string
}
/**
 * Zero-trust Content Disarm and Reconstruction pipeline.
 * Safely processes untrusted bytes and guarantees output is mathematically safe.
 *
 * @param rawBuffer The untrusted file buffer
 * @param expectedFormat (Optional) Strict format hint (e.g. "pdf", "png"). Rejects if mismatch.
 */
export declare function disarm(rawBuffer: Uint8Array, expectedFormat?: string | undefined | null): NodeDisarmResult

/**
 * Async, non-blocking Content Disarm and Reconstruction pipeline.
 *
 * Returns a `Promise<NodeDisarmResult>` that resolves on a background
 * thread pool, leaving the Node.js event loop completely free.
 *
 * @example
 * ```ts
 * import { disarmAsync } from 'gatekeeper-cdr';
 * import { readFileSync } from 'fs';
 *
 * const input = readFileSync('suspicious.jpg');
 * const result = await disarmAsync(input);
 * // result.buffer is the safe, sanitized output
 * ```
 */
export declare function disarmAsync(rawBuffer: Buffer): Promise<NodeDisarmResult>
